name: Build APK

on:
  push:
    branches:
      - main  # หรือเปลี่ยนเป็นชื่อ branch ที่คุณใช้อยู่

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build release APK
        run: cd android && chmod +x ./gradlew && ./gradlew assembleRelease
